Improved sso user generation and fixed ULA assigning

diff --git a/iservchk/40iserv3/90ipv6-support_api b/iservchk/40iserv3/90ipv6-support_api
--- a/iservchk/40iserv3/90ipv6-support_api
+++ b/iservchk/40iserv3/90ipv6-support_api
@@ -4,11 +4,14 @@ ChPerm 0600 root:root /var/lib/iserv/pwd/ipv6sso.pwd
 Test "ipv6 api user for sso"
   iservapiuser | grep -qE "ipv6sso\s*127.0.0.1"
   ---
-  iservapiuser add ipv6sso 127.0.0.1 > /var/lib/iserv/pwd/ipv6sso.pwd
+  PASSWORD="$(iservapiuser add ipv6sso 127.0.0.1)"
+  EXITCODE=$?
+  [[ $EXITCODE -gt 0 ]] && exit 1 
+  echo $PASSWORD > /var/lib/iserv/pwd/ipv6sso.pwd
 
 Test "ipv6 api password stored"
   [ -s /var/lib/iserv/pwd/ipv6sso.pwd ]
   ---
-  echo "api password for ipv6sso is missing. This will may cause unexpected "\
-   "errors." 1>&2
+  echo "api password for ipv6sso is missing. This will may cause unexpected"\
+      "errors." 1>&2
 
